name: deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploySCF:
    runs-on: ubuntu-latest
    env:
      SERVERLESS_PLATFORM_VENDOR: tencent
      TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
      TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: ENV
        run: echo $GITHUB_RUN_ID
      - name: Install serverless cli
        run: sudo npm i serverless -g
      - name: Deploy and invoke SCF
        run: sls deploy
